### ISSUE TITLE
can't run tests

### ISSUE THREAD

**Issue by codedubs** [learn-co-curriculum/javascript-intro-to-looping#41] opened 2018-02-07 08:57 UTC
says local tests are passed but have nothing logged to loops.js

**Comment by drakeltheryuujin** [comment] 2018-07-27 16:43
Hi there,

It looks like you've moved past this lesson, but I'm unable to reproduce the issue, so I'm going to close it for now.

If it's still an issue and you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

Thanks for contributing! 💙

**Closed by drakeltheryuujin** 2018-07-27 16:43 UTC
Labels: Product
